//! # Proxie String Utils — Safe Rust FFI Wrapper
//!
//! This crate provides a **safe Rust API** around a C++ string utilities library.
//! All unsafe FFI calls are confined to internal implementation — the public API
//! is 100% safe Rust.
//!
//! ## Architecture
//!
//! ```text
//! ┌─────────────────────┐     ┌──────────────────────┐     ┌────────────────────┐
//! │  Your Rust Code     │────▶│  Safe Wrapper (this)  │────▶│  C++ Library       │
//! │  reverse_string()   │     │  CString ↔ *c_char    │     │  str_reverse()     │
//! └─────────────────────┘     └──────────────────────┘     └────────────────────┘
//! ```
//!
//! ## Memory Ownership
//!
//! - Functions that **return strings** (reverse_string, uppercase): C++ allocates
//!   memory via `malloc`. The safe wrapper copies the data into a Rust `String`
//!   and then immediately calls `free_string()` to release the C++ memory.
//!   → **No memory leaks, no double frees.**
//!
//! - Functions that **return integers** (string_length, vowel_count): No allocation
//!   happens on the C++ side — just a return value.

use std::ffi::{CStr, CString, NulError};
use std::fmt;
use std::str::Utf8Error;

// ═══════════════════════════════════════════════════════════════════
// LAYER 1: Raw FFI Bindings (auto-generated by bindgen)
// ═══════════════════════════════════════════════════════════════════
// This include! macro inserts the generated Rust code from bindgen.
// The generated code contains `extern "C"` function declarations
// that tell Rust how to call our C++ functions.
//
// WHY include! instead of a separate module?
// → It's the standard pattern for bindgen. The file is generated
//   at build time into $OUT_DIR, which only include! can access.
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

// ═══════════════════════════════════════════════════════════════════
// CUSTOM ERROR TYPE
// ═══════════════════════════════════════════════════════════════════
// Instead of panicking on errors, we return Result<T, StringUtilError>.
// This is idiomatic Rust — let the caller decide how to handle errors.

/// Errors that can occur when using string utility functions.
///
/// ## Interview Explanation
/// We define a custom error enum because:
/// 1. FFI calls can fail in multiple ways (null bytes, invalid UTF-8, null pointers)
/// 2. Using Result<T, E> is idiomatic Rust (no panics, no crashes)
/// 3. Each variant carries context about WHAT went wrong
#[derive(Debug)]
pub enum StringUtilError {
    /// The input string contains an interior null byte ('\0').
    /// CString requires exactly ONE null byte at the end — any null byte
    /// inside the string would truncate it when passed to C++.
    NullByte(NulError),

    /// The C++ function returned a string that isn't valid UTF-8.
    /// Rust strings must be valid UTF-8. This shouldn't happen with ASCII
    /// operations, but we handle it defensively.
    InvalidUtf8(Utf8Error),

    /// The C++ function returned a null pointer.
    /// This typically means malloc() failed (out of memory).
    NullPointer,
}

// Implement Display for our error type (required for good error messages)
impl fmt::Display for StringUtilError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            StringUtilError::NullByte(e) => write!(f, "Input contains null byte: {}", e),
            StringUtilError::InvalidUtf8(e) => write!(f, "C++ returned invalid UTF-8: {}", e),
            StringUtilError::NullPointer => write!(f, "C++ returned null pointer (allocation failure)"),
        }
    }
}

// Implement std::error::Error so our type works with the ? operator
// and integrates with Rust's error handling ecosystem
impl std::error::Error for StringUtilError {}

// Allow automatic conversion from NulError → StringUtilError
// This lets us use the ? operator on CString::new()
impl From<NulError> for StringUtilError {
    fn from(e: NulError) -> Self {
        StringUtilError::NullByte(e)
    }
}

// Allow automatic conversion from Utf8Error → StringUtilError
// This lets us use the ? operator on CStr::to_str()
impl From<Utf8Error> for StringUtilError {
    fn from(e: Utf8Error) -> Self {
        StringUtilError::InvalidUtf8(e)
    }
}

// ═══════════════════════════════════════════════════════════════════
// LAYER 2: Safe Public API
// ═══════════════════════════════════════════════════════════════════
// These functions are the ONLY public interface. They:
//   1. Convert Rust types → C types (before FFI call)
//   2. Call the unsafe C++ function
//   3. Convert C types → Rust types (after FFI call)
//   4. Handle errors and free C++ memory

/// Returns the length of the given string.
///
/// # How it works (step by step)
/// 1. Convert `&str` to `CString` — adds a null terminator that C++ expects
/// 2. Call the C++ `str_length()` function (unsafe FFI)
/// 3. Return the integer result (no memory to free — C++ didn't allocate anything)
///
/// # Errors
/// Returns `StringUtilError::NullByte` if `input` contains a null byte.
///
/// # Examples
/// ```
/// let len = proxie_string_utils::string_length("hello").unwrap();
/// assert_eq!(len, 5);
/// ```
pub fn string_length(input: &str) -> Result<i32, StringUtilError> {
    // Step 1: Convert Rust &str → CString
    // CString::new() adds a '\0' at the end (C strings are null-terminated)
    // It fails if the input already contains '\0' (interior null byte)
    let c_input = CString::new(input)?;

    // Step 2: Call the unsafe C++ function
    // as_ptr() returns a *const c_char pointing to the CString's data
    // SAFETY: c_input is a valid, null-terminated C string that lives
    //         for the duration of this function call
    let result = unsafe { ffi::str_length(c_input.as_ptr()) };

    // Step 3: Return the result (no cleanup needed — no allocation on C++ side)
    Ok(result)
}

/// Returns a new string with all characters reversed.
///
/// # How it works (step by step)
/// 1. Convert `&str` to `CString`
/// 2. Call C++ `str_reverse()` — C++ allocates a NEW string via malloc
/// 3. Check for null pointer (malloc failure)
/// 4. Convert the C string back to a Rust `String` (copies the data)
/// 5. Free the C++ allocated memory via `free_string()`
/// 6. Return the Rust-owned String
///
/// # Memory Safety
/// The key insight: we copy the data into Rust-owned memory (step 4) BEFORE
/// freeing the C++ memory (step 5). This ensures we never access freed memory.
///
/// # Errors
/// - `NullByte` — input contains a null byte
/// - `NullPointer` — C++ malloc failed
/// - `InvalidUtf8` — reversed string isn't valid UTF-8
///
/// # Examples
/// ```
/// let reversed = proxie_string_utils::reverse_string("hello").unwrap();
/// assert_eq!(reversed, "olleh");
/// ```
pub fn reverse_string(input: &str) -> Result<String, StringUtilError> {
    // Step 1: Convert Rust &str → CString
    let c_input = CString::new(input)?;

    // Step 2: Call the unsafe C++ function
    // SAFETY: c_input is a valid null-terminated C string
    let result_ptr = unsafe { ffi::str_reverse(c_input.as_ptr()) };

    // Step 3: Check for null pointer (C++ allocation failure)
    if result_ptr.is_null() {
        return Err(StringUtilError::NullPointer);
    }

    // Step 4: Convert C string → Rust String
    // CStr::from_ptr() creates a borrowed view of the C string
    // .to_str()? converts it to a Rust &str (fails if not valid UTF-8)
    // .to_owned() copies the data into a new Rust String
    // SAFETY: result_ptr is non-null and points to a valid null-terminated string
    //         allocated by our C++ code
    let result = unsafe { CStr::from_ptr(result_ptr) }
        .to_str()?
        .to_owned();

    // Step 5: Free the C++ allocated memory
    // CRITICAL: We do this AFTER to_owned() has copied the data.
    // If we freed first and then tried to read, we'd have use-after-free!
    // SAFETY: result_ptr was allocated by C++ malloc in str_reverse()
    unsafe { ffi::free_string(result_ptr) };

    // Step 6: Return the Rust-owned String
    Ok(result)
}

/// Counts the number of vowels (a, e, i, o, u — both cases) in the string.
///
/// # How it works (step by step)
/// 1. Convert `&str` to `CString`
/// 2. Call C++ `count_vowels()` (returns an integer, no allocation)
/// 3. Return the count
///
/// # Errors
/// Returns `StringUtilError::NullByte` if `input` contains a null byte.
///
/// # Examples
/// ```
/// let count = proxie_string_utils::vowel_count("hello world").unwrap();
/// assert_eq!(count, 3);
/// ```
pub fn vowel_count(input: &str) -> Result<i32, StringUtilError> {
    // Step 1: Convert Rust &str → CString
    let c_input = CString::new(input)?;

    // Step 2: Call the unsafe C++ function
    // SAFETY: c_input is a valid null-terminated C string
    let result = unsafe { ffi::count_vowels(c_input.as_ptr()) };

    // Step 3: Return the result
    Ok(result)
}

/// Returns a new string with all characters converted to uppercase.
///
/// # How it works (step by step)
/// 1. Convert `&str` to `CString`
/// 2. Call C++ `to_uppercase()` — C++ allocates a NEW string via malloc
/// 3. Check for null pointer (malloc failure)
/// 4. Convert C string → Rust String (copies data into Rust-owned memory)
/// 5. Free C++ memory via `free_string()`
/// 6. Return the Rust-owned String
///
/// # Memory Safety
/// Same pattern as reverse_string: copy first, then free.
///
/// # Errors
/// - `NullByte` — input contains a null byte
/// - `NullPointer` — C++ malloc failed
/// - `InvalidUtf8` — uppercase string isn't valid UTF-8
///
/// # Examples
/// ```
/// let upper = proxie_string_utils::uppercase("hello").unwrap();
/// assert_eq!(upper, "HELLO");
/// ```
pub fn uppercase(input: &str) -> Result<String, StringUtilError> {
    // Step 1: Convert Rust &str → CString
    let c_input = CString::new(input)?;

    // Step 2: Call the unsafe C++ function
    // SAFETY: c_input is a valid null-terminated C string
    let result_ptr = unsafe { ffi::to_uppercase(c_input.as_ptr()) };

    // Step 3: Check for null pointer
    if result_ptr.is_null() {
        return Err(StringUtilError::NullPointer);
    }

    // Step 4: Convert C string → Rust String
    // SAFETY: result_ptr is non-null and points to a valid null-terminated string
    let result = unsafe { CStr::from_ptr(result_ptr) }
        .to_str()?
        .to_owned();

    // Step 5: Free C++ allocated memory
    // SAFETY: result_ptr was allocated by C++ malloc in to_uppercase()
    unsafe { ffi::free_string(result_ptr) };

    // Step 6: Return Rust-owned String
    Ok(result)
}

// ═══════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════
// #[cfg(test)] means this module is ONLY compiled when running `cargo test`.
// It's completely stripped from the release binary.

#[cfg(test)]
mod tests {
    use super::*;

    // ─────────────────────────────────────────────────────────
    // str_length tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_str_length_basic() {
        assert_eq!(string_length("hello").unwrap(), 5);
        assert_eq!(string_length("rust").unwrap(), 4);
        assert_eq!(string_length("a").unwrap(), 1);
    }

    #[test]
    fn test_str_length_empty() {
        assert_eq!(string_length("").unwrap(), 0);
    }

    #[test]
    fn test_str_length_with_spaces() {
        assert_eq!(string_length("hello world").unwrap(), 11);
        assert_eq!(string_length("  spaces  ").unwrap(), 10);
    }

    #[test]
    fn test_str_length_special_chars() {
        assert_eq!(string_length("hello!@#$%").unwrap(), 10);
        assert_eq!(string_length("123-456").unwrap(), 7);
    }

    // ─────────────────────────────────────────────────────────
    // str_reverse tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_str_reverse_basic() {
        assert_eq!(reverse_string("hello").unwrap(), "olleh");
        assert_eq!(reverse_string("rust").unwrap(), "tsur");
        assert_eq!(reverse_string("abc").unwrap(), "cba");
    }

    #[test]
    fn test_str_reverse_empty() {
        assert_eq!(reverse_string("").unwrap(), "");
    }

    #[test]
    fn test_str_reverse_single_char() {
        assert_eq!(reverse_string("a").unwrap(), "a");
        assert_eq!(reverse_string("Z").unwrap(), "Z");
    }

    #[test]
    fn test_str_reverse_palindrome() {
        // A palindrome reversed should equal itself
        assert_eq!(reverse_string("racecar").unwrap(), "racecar");
        assert_eq!(reverse_string("madam").unwrap(), "madam");
    }

    #[test]
    fn test_str_reverse_with_spaces() {
        assert_eq!(reverse_string("hello world").unwrap(), "dlrow olleh");
    }

    #[test]
    fn test_str_reverse_special_chars() {
        assert_eq!(reverse_string("ab!cd").unwrap(), "dc!ba");
        assert_eq!(reverse_string("123").unwrap(), "321");
    }

    // ─────────────────────────────────────────────────────────
    // count_vowels tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_count_vowels_basic() {
        assert_eq!(vowel_count("hello").unwrap(), 2);        // e, o
        assert_eq!(vowel_count("hello world").unwrap(), 3);  // e, o, o
    }

    #[test]
    fn test_count_vowels_empty() {
        assert_eq!(vowel_count("").unwrap(), 0);
    }

    #[test]
    fn test_count_vowels_no_vowels() {
        assert_eq!(vowel_count("bcdfg").unwrap(), 0);
        assert_eq!(vowel_count("rhythm").unwrap(), 0);
        assert_eq!(vowel_count("123!@#").unwrap(), 0);
    }

    #[test]
    fn test_count_vowels_all_vowels() {
        assert_eq!(vowel_count("aeiou").unwrap(), 5);
        assert_eq!(vowel_count("AEIOU").unwrap(), 5);
    }

    #[test]
    fn test_count_vowels_mixed_case() {
        assert_eq!(vowel_count("AeIoU").unwrap(), 5);
        assert_eq!(vowel_count("HeLLo WoRLd").unwrap(), 3);
    }

    #[test]
    fn test_count_vowels_single_char() {
        assert_eq!(vowel_count("a").unwrap(), 1);
        assert_eq!(vowel_count("b").unwrap(), 0);
    }

    // ─────────────────────────────────────────────────────────
    // to_uppercase tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_to_uppercase_basic() {
        assert_eq!(uppercase("hello").unwrap(), "HELLO");
        assert_eq!(uppercase("rust").unwrap(), "RUST");
    }

    #[test]
    fn test_to_uppercase_empty() {
        assert_eq!(uppercase("").unwrap(), "");
    }

    #[test]
    fn test_to_uppercase_already_upper() {
        assert_eq!(uppercase("HELLO").unwrap(), "HELLO");
        assert_eq!(uppercase("ABC").unwrap(), "ABC");
    }

    #[test]
    fn test_to_uppercase_mixed_case() {
        assert_eq!(uppercase("HeLLo WoRLd").unwrap(), "HELLO WORLD");
    }

    #[test]
    fn test_to_uppercase_single_char() {
        assert_eq!(uppercase("a").unwrap(), "A");
        assert_eq!(uppercase("Z").unwrap(), "Z");
    }

    #[test]
    fn test_to_uppercase_with_numbers() {
        // Numbers and symbols should pass through unchanged
        assert_eq!(uppercase("hello123").unwrap(), "HELLO123");
        assert_eq!(uppercase("test!@#").unwrap(), "TEST!@#");
    }

    #[test]
    fn test_to_uppercase_spaces() {
        assert_eq!(uppercase("hello world").unwrap(), "HELLO WORLD");
    }

    // ─────────────────────────────────────────────────────────
    // Error handling tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_null_byte_in_input() {
        // Strings containing '\0' should return NullByte error
        let result = string_length("hello\0world");
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), StringUtilError::NullByte(_)));

        let result = reverse_string("test\0data");
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), StringUtilError::NullByte(_)));

        let result = vowel_count("abc\0def");
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), StringUtilError::NullByte(_)));

        let result = uppercase("hello\0world");
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), StringUtilError::NullByte(_)));
    }

    // ─────────────────────────────────────────────────────────
    // Stress / Long string tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_long_string() {
        // Test with a 10,000 character string to verify no buffer overflows
        let long_input: String = "a".repeat(10_000);
        assert_eq!(string_length(&long_input).unwrap(), 10_000);

        let reversed = reverse_string(&long_input).unwrap();
        assert_eq!(reversed.len(), 10_000);
        assert_eq!(reversed, long_input); // "aaa...a" reversed = "aaa...a"

        assert_eq!(vowel_count(&long_input).unwrap(), 10_000); // all 'a's are vowels

        let upper = uppercase(&long_input).unwrap();
        assert_eq!(upper, "A".repeat(10_000));
    }

    #[test]
    fn test_long_mixed_string() {
        let long_input: String = "Hello World! ".repeat(1000);
        let len = string_length(&long_input).unwrap();
        assert_eq!(len, 13_000);

        // Verify reverse works on long strings
        let reversed = reverse_string(&long_input).unwrap();
        assert_eq!(reversed.len(), 13_000);

        // Verify uppercase works on long strings
        let upper = uppercase(&long_input).unwrap();
        assert_eq!(upper, "HELLO WORLD! ".repeat(1000));
    }

    // ─────────────────────────────────────────────────────────
    // Combined / integration tests
    // ─────────────────────────────────────────────────────────

    #[test]
    fn test_reverse_then_reverse_is_identity() {
        let input = "Hello, World!";
        let reversed = reverse_string(input).unwrap();
        let double_reversed = reverse_string(&reversed).unwrap();
        assert_eq!(double_reversed, input);
    }

    #[test]
    fn test_uppercase_preserves_length() {
        let input = "hello world";
        let upper = uppercase(input).unwrap();
        assert_eq!(
            string_length(input).unwrap(),
            string_length(&upper).unwrap()
        );
    }

    #[test]
    fn test_vowel_count_case_insensitive() {
        // Same string in different cases should have same vowel count
        let lower = vowel_count("hello").unwrap();
        let upper = vowel_count("HELLO").unwrap();
        let mixed = vowel_count("HeLLo").unwrap();
        assert_eq!(lower, upper);
        assert_eq!(upper, mixed);
    }
}
